### PR TITLE
Fix uploading of sprockets manifest file

### LINKED ISSUE #396: AssetSync is not uploading .sprockets-manifest-*.json with include_manifest = true
I am trying to get the AssetSync upload working. At one point, I did see this working about a week or two ago, but when I did some spelunking I'm not how it could work right now. I have a hunch Sprockets might have changed something under the hood.

Inside of storage.rb, the method: `get_manifest_path` is passed to always_upload_files, so that we can fetch the manifest file when the config option `include_manifest` is true.

Now, from what I can tell, get_manifest_path is reaching into the Sprockets manifest and pulling out the [filename](https://github.com/AssetSync/asset_sync/blob/master/lib/asset_sync/storage.rb#L48).

This is returning a full filepath for me though, and looks something like: `/Users/dlinch/work/project-name/public/assets/.sprockets-manifest-7fb3728dde636cbfcd21324e2e0e7df2.json1`

So when that file is checked inside the upload_files method, there is a check for:
`File.file? "#{path}/#{f}"`, which will return false because every other file is a simple filename that it throws the relative path behind, and that will not work for this. I did check the Sprockets manifest generation in my local rails console, and `filename` is returning a full path there as well.

### PR DESCRIPTION
**Pull request by PikachuEXE**
Fixes #396

Update the input value of `public_path` to an absolute path on assignment
via `Rails.root` or `Dir.pwd` (rails less case)

### CODE REVIEW

File: lib/asset_sync/config.rb [hunk 1]
```diff
@@ -175,6 +174,18 @@ def public_path
       @public_path || ::Rails.public_path
     end
 
+    def public_path=(path)
+      # Generate absolute path even when relative path passed in
+      # Required for generating relative sprockets manifest path
+      @public_path = if path.absolute?
```
Comment (dlinch) [inline lib/asset_sync/config.rb]: I would have actually expected this to be a string relative path `'./public'` if we are setting it in an initializer.

I tested in my console, and Pathname seems to be idempotent. So we should probably pass path into Pathname so we can call absolute on it, or it will blow up on a regular string.
The code below returns a Pathname instance, which has the `.absolute` method defined.
```suggestion
pathname = Pathname.new(path)
@public_path = if path.absolute?
```

Tested in rails console:
```ruby
Pathname.new(Pathname.new('./public'))
# => #<Pathname:./public>
```

I assume step 2 would be to add this to the config options listed [here](https://github.com/AssetSync/asset_sync#custom-rails-initializer-configinitializersasset_syncrb). A comment to know this can handle Pathname instances or a relative path from project root would be helpful as well.

Comment (PikachuEXE) [reply lib/asset_sync/config.rb]: Yup I missed that since the spec used `Pathname` in setup
Thanks for reminding me that

Updated code, spec setup and doc

**Comment by PikachuEXE** [comment]
Build failed but only on JRuby due to `Could not find jruby-openssl`
Not related to the code

**Comment by PikachuEXE** [comment]
Released in `3.9.1`
